// Mocks generated by Mockito 5.3.2 from annotations
// in deptech_app/test/infrastructure/dal/daos/note/repositories/note_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:deptech_app/infrastructure/dal/daos/note/models/note_model.dart'
    as _i5;
import 'package:deptech_app/infrastructure/dal/daos/user/models/base_list_resp.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

import 'note_repository_test.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [NoteDbDataSourceTest].
///
/// See the documentation for Mockito's code generation for more information.
class MockNoteDbDataSourceTest extends _i1.Mock
    implements _i2.NoteDbDataSourceTest {
  MockNoteDbDataSourceTest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseListResp<_i5.NoteModel>?> getNotesByUserId(int? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNotesByUserId,
          [userId],
        ),
        returnValue: _i3.Future<_i4.BaseListResp<_i5.NoteModel>?>.value(),
      ) as _i3.Future<_i4.BaseListResp<_i5.NoteModel>?>);
  @override
  _i3.Future<_i5.NoteModel?> getNoteById(int? noteId) => (super.noSuchMethod(
        Invocation.method(
          #getNoteById,
          [noteId],
        ),
        returnValue: _i3.Future<_i5.NoteModel?>.value(),
      ) as _i3.Future<_i5.NoteModel?>);
  @override
  _i3.Future<int?> insertNote(_i5.NoteModel? data) => (super.noSuchMethod(
        Invocation.method(
          #insertNote,
          [data],
        ),
        returnValue: _i3.Future<int?>.value(),
      ) as _i3.Future<int?>);
  @override
  _i3.Future<String?> updateNote(_i5.NoteModel? data) => (super.noSuchMethod(
        Invocation.method(
          #updateNote,
          [data],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);
  @override
  _i3.Future<int?> deleteNote(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteNote,
          [id],
        ),
        returnValue: _i3.Future<int?>.value(),
      ) as _i3.Future<int?>);
}
