name: deptech_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  sizer: ^2.0.15
  animate_do: ^3.0.2
  sqflite: ^2.2.2
  path_provider: ^2.0.11
  equatable: ^2.0.5
  mockito: ^5.3.2
  intl: ^0.18.0
  timezone: ^0.9.0
  localstorage: ^4.0.0+1
  flutter_local_notifications: ^13.0.0

dev_dependencies: 
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/icons/

